// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dasarapaymenttracker.Data;

#nullable disable

namespace dasarapaymenttracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dasarapaymenttracker.Models.PayMonth", b =>
                {
                    b.Property<int>("PayMonthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayMonthId"));

                    b.Property<DateOnly>("MonthStartDate")
                        .HasColumnType("date");

                    b.HasKey("PayMonthId");

                    b.HasIndex("MonthStartDate")
                        .IsUnique();

                    b.ToTable("PayMonths");
                });

            modelBuilder.Entity("dasarapaymenttracker.Models.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentStatusId"));

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PayMonthId")
                        .HasColumnType("integer");

                    b.Property<int>("PeerId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PaymentStatusId");

                    b.HasIndex("PersonId", "PayMonthId")
                        .IsUnique();

                    b.ToTable("PaymentStatuses");
                });

            modelBuilder.Entity("dasarapaymenttracker.Models.Peer", b =>
                {
                    b.Property<int>("PeerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeerId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PeerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PeerId");

                    b.HasIndex("PeerName")
                        .IsUnique();

                    b.ToTable("Peers");
                });

            modelBuilder.Entity("dasarapaymenttracker.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PeerId")
                        .HasColumnType("integer");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonId");

                    b.HasIndex("PeerId", "PersonName")
                        .IsUnique();

                    b.ToTable("People");
                });

            modelBuilder.Entity("dasarapaymenttracker.Models.PaymentStatus", b =>
                {
                    b.HasOne("dasarapaymenttracker.Models.Person", null)
                        .WithMany("PaymentStatuses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dasarapaymenttracker.Models.Person", b =>
                {
                    b.HasOne("dasarapaymenttracker.Models.Peer", "Peer")
                        .WithMany("People")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });

            modelBuilder.Entity("dasarapaymenttracker.Models.Peer", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("dasarapaymenttracker.Models.Person", b =>
                {
                    b.Navigation("PaymentStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
